export enum PageRoute {
  LOGIN = "/login",
  DASHBOARD_METRICS = "/dashboard-metrics",
  PROFILE = "/profile",
  COURSES = "/courses",
  ARTICLES = "/articles",
  QUESTIONS = "/questions",
  QUIZZES = "/quizzes",
  QUESTION_BANK = "/question-bank",
  USER_MANAGEMENT = "/user-management",
  ROLE_PERMISSIONS = "/role-permissions",
  SETTINGS = "/settings",
  SYSTEM_SETTINGS = "/settings",
  QUIZ_MANAGEMENT = "/quizzes",
  CATEGORY_MANAGEMENT = "/categories/management",
  COURSE_MANAGEMENT = "/courses/manage",
  QUESTION_BANK_MANAGEMENT = "/question-bank",
}
