export enum PageRoute {
  LOGIN = "/login",
  DASHBOARD_METRICS = "/dashboard-metrics",
  PROFILE = "/profile",
  COURSES = "/courses",
  HISTORY = "/history",
  ARTICLES = "/articles",
  QUESTIONS = "/questions",
  QUESTION_BANK = "/question-bank",
  USER_MANAGEMENT = "/user-management",
  ROLE_PERMISSIONS = "/role-permissions",
  SETTINGS = "/settings",
  SYSTEM_SETTINGS = "/settings",
  QUIZ_MANAGEMENT = "/quizzes",
  QA_MANAGEMENT = "/questions/management",
  CATEGORY_MANAGEMENT = "/categories/management",
  COURSE_MANAGEMENT = "/courses/management",
  QUESTION_BANK_MANAGEMENT = "/question-bank",
  ARTICLE_MANAGEMENT = "/articles/management",
  DOCUMENT_MANAGEMENT = "/documents/management",
  DOCUMENTS = "/documents"
}
